name: HMTAPI
version: '${project.version}'
main: de.jumpstone.hmtapi.HMTAPI
api-version: '1.21'
depend: [PlaceholderAPI]
permissions:
  hmtapi.reload:
    description: "Reload the plugin to apply changes you make in config.yml"

commands:
  hmtapi:
    description: "The main command of HMT API."
    permission: "hmtapi.reload"
    permission-message: "You do not have permission to use this command."
    usage: /hmtapi <reload>